DROP TABLE IF EXISTS `USER_QUEST_INFO`;

DROP TABLE IF EXISTS `USER_QUEST_INVENTORY`;

DROP TABLE IF EXISTS `USER_QUEST_RECORD`;

ALTER TABLE `GUILD_INFO` add `CURRENT_QUEST_STAGE` smallint(10) unsigned DEFAULT NULL;
  
  CREATE TABLE `GUILD_CURRENT_QUEST_STAGE` (
  `ID_QUEST_REQUIREMENT` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ID_GUILD` int(11) unsigned NOT NULL,
  `REQUIREMENT_TYPE` tinyint(4) UNSIGNED NOT NULL,
  `QUANTITY_COMPLETED` INT(10) UNSIGNED NOT NULL,
  `REQUIREMENT_INDEX` INT(10) UNSIGNED DEFAULT NULL,
  KEY `ID_QUEST_REQUIREMENT` (`ID_QUEST_REQUIREMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `QUEST_REQUIREMENT` (
  `ID_QUEST_REQUIREMENT` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `KEY` varchar(30) DEFAULT NULL,
  KEY `ID_QUEST_REQUIREMENT` (`ID_QUEST_REQUIREMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


/* INSERT QUEST REQUIREMENTS */
INSERT INTO QUEST_REQUIREMENT
( ID_QUEST_REQUIREMENT, `KEY`)
VALUES
(1, "NPC"),
(2, "OBJ"),
(3, "FRAG_NEUTRAL"),
(4, "FRAG_CIUDADANO"),
(5, "FRAG_CRIMINAL"),
(6, "FRAG_ARMADA"),
(7, "FRAG_LEGION");