ALTER TABLE `GUILD_INFO` ADD `RANKING_POINTS` INT(10) UNSIGNED DEFAULT 0;
ALTER TABLE USER_STATS CHANGE PLAYER_POINTS RANKING_POINTS INT(10) UNSIGNED DEFAULT 0;	

UPDATE GUILD_INFO SET RANKING_POINTS = 1000;
UPDATE USER_STATS SET RANKING_POINTS = 1000;