ALTER TABLE `GUILD_INFO` ADD `CURRENT_QUEST_SECONDS_LEFT` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `GUILD_QUEST_COMPLETED` ADD `TOTAL_SECONDS` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `GUILD_QUEST_COMPLETED` ADD `STARTED_DATE` datetime DEFAULT NULL AFTER ID_QUEST;