ALTER TABLE `user_faction`	ADD COLUMN `ALIGNMENT` TINYINT(4) UNSIGNED NULL DEFAULT NULL AFTER `ID_USER`;
ALTER TABLE `user_faction`	ADD COLUMN `NEUTRAL_KILLED` MEDIUMINT(9) NULL DEFAULT NULL AFTER `CHAOS`;

-- Update existing values in the table.
UPDATE user_faction SET ALIGNMENT = 1 WHERE ARMY = 0 AND CHAOS = 0;
UPDATE user_faction SET ALIGNMENT = 2 WHERE ARMY = 1 AND CHAOS = 0;
UPDATE user_faction SET ALIGNMENT = 3 WHERE ARMY = 0 AND CHAOS = 1;

UPDATE user_faction SET NEUTRAL_KILLED = 0;

-- Remove the USER_REPUTATION table that is not in use anymore
DROP TABLE IF EXISTS `USER_REPUTATION`;